### PR TITLE
Build for multiple versions of Minecraft

### LINKED ISSUE #47: Versions
May I ask for a broader spectrum of support MC version ? Like 1.20.1-1.20.2-1.20.4 and 1.21 ? 1.21 only is a bit restrictive

### PR DESCRIPTION
**Pull request by Jckf**
image

Closes #47

### CODE REVIEW

**Comment by kccricket** [comment]
@Jckf Forgive the intrusion, because I'm not an experienced plugin developer. But, what's the benefit to building multiple jars this way, rather than building one jar that simply avoids using Spigot/Bukkit API features that aren't supported in the earliest version of Minecraft you're targeting? It's my understanding that the api-version property indicates the earliest API version the plugin is targeting, rather than the actual version of the API it's built against.

**Comment by Jckf** [comment]
@kccricket There is currently no real benefit, because I am not utilizing it to introduce any changes to the code. Distant Horizons has some differences between versions, so it _could_ become necessary, but their devs are working on making it more consistent 🙏

**Comment by nikp123** [comment]
Also for clarity sake, in case you run into a version earlier than 1.20.6 (AFAIK) you'll need to specify a broader API version (ie. ``1.20``) in the pom file for it to be properly be recognized by Bukkit/PaperMC/etc.

**Comment by Jckf** [comment]
@nikp123 We spoke on Discord, but just so the conversation exists on Github as well: This was addressed here https://github.com/Jckf/DH-Support/commit/e5989134cc268fbec5d05ba438226ecc8c1d0bd7 :)

**Pull request merged**
